routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CastController;
use App\Http\Controllers\FilmController;
use App\Http\Controllers\GenreController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\UlasanController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index']);
Route::get('/register', [AuthController::class, 'register']);
Route::post('/welcome', [AuthController::class, 'welcome']);

Route::view('/data-table', 'data-table');
Route::view('/table', 'table');

Route::middleware(['auth'])->group(function () {
  // route untuk mengarah ke form tambah cast
  Route::get('/cast/create', [CastController::class, 'create'])->name('cast.create');
  // route untuk menyimpan data inputan ke db
  Route::post('/cast', [CastController::class, 'store'])->name('cast.store');
  // menampilkan semua data yang di db
  Route::get('/cast', [CastController::class, 'index'])->name('cast.index');
  // detail cast berdasarkan id
  Route::get('/cast/{cast_id}', [CastController::class, 'show'])->name('cast.show');
  // untuk mengarah ke halaman form update berdasarkan id
  Route::get('/cast/{cast_id}/edit', [CastController::class, 'edit'])->name('cast.edit');
  // untuk update data
  Route::put('/cast/{cast_id}', [CastController::class, 'update'])->name('cast.update');
  // menghapus data
  Route::delete('/cast/{cast_id}', [CastController::class, 'destroy'])->name('cast.destroy');

  Route::resource('profile', ProfileController::class)->only('index', 'update');
  Route::resource('genre', GenreController::class);

  Route::post('/ulasan/{berita_id}', [UlasanController::class, 'store']);
});


Route::resource('film', FilmController::class);

Auth::routes();

app/Models/Genre.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Genre extends Model
{
    use HasFactory;

    protected $table = "genre";
    protected $fillable = ["nama", "deskripsi"];

    public function film()
    {
        return $this->hasMany(Film::class, 'genre_id');
    }
}

app/Http/Controllers/GenreController.php
<?php

namespace App\Http\Controllers;

use App\Models\Genre;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class GenreController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $genre = Genre::all();
        return view('genre.index', ['genre' => $genre]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('genre.tambah');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => ['required', 'max:255'],
            'deskripsi' => ['required'],
        ]);

        DB::table('genre')->insert([
            'nama' => $request['nama'],
            'deskripsi' => $request['deskripsi'],
        ]);

        return redirect('/genre');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $genre = Genre::find($id);

        return view('genre.show', ['genre' => $genre]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $genre = Genre::find($id);

        return view('genre.edit', ['genre' => $genre]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama' => ['required', 'max:255'],
            'deskripsi' => ['required'],
        ]);

        DB::table('genre')
            ->where('id', $id)
            ->update(
                [
                    'nama' => $request['nama'],
                    'deskripsi' => $request['deskripsi'],
                ]
            );
        return redirect('/genre');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table('genre')->where('id', '=', $id)->delete();

        return redirect('/genre');
    }
}

resources/views/genre/edit.blade.php
@extends('layouts.master')

@section('title')
    Halaman edit Genre
@endsection

@section('content')
<form method="post" action="/genre/{{ $genre->id }}">
  @csrf
  @method('put')
  <div class="form-group">
    <label for="nama">Nama genre</label>
    <input type="text" class="form-control" name="nama" id="nama" value="{{ old('nama', $genre->nama) }}">
  </div>
  @error('nama')
      <div class="alert alert-danger">{{ $message }}</div>
  @enderror
  <div class="form-group">
    <label for="deskripsi">deskripsi</label>
    <input type="text" class="form-control" name="deskripsi" id="deskripsi" value="{{ old('deskripsi', $genre->deskripsi) }}">
  </div>
  @error('deskripsi')
      <div class="alert alert-danger">{{ $message }}</div>
  @enderror
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
@endsection

resources/views/genre/index.blade.php
@extends('layouts.master')

@section('title')
    Halaman Tampil Genre
@endsection

@section('content')

<a href="{{ route('genre.create') }}" class="btn btn-primary btn-sm my-3">Tambah Genre</a>

<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nama</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
        @forelse ($genre as $key => $value)
        <tr>
          <th scope="row">{{ $key + 1 }}</th>
          <td>{{ $value->nama }}</td>
          <td>
            <form action="{{ route('genre.destroy', $value->id) }}" method="post">
              @csrf
              @method('delete')
            <a href="{{ route('genre.show', $value->id) }}" class="btn btn-info btn-sm">Detail</a>
              <a href="{{ route('genre.edit', $value->id) }}" class="btn btn-warning btn-sm">Edit</a>
              <input type="submit" value="Delete" class="btn btn-danger btn-sm">
            </form>
          </td>
        </tr>
        @empty
            <h1>Data Kosong</h1>
        @endforelse
    </tbody>
  </table>
@endsection

resources/views/genre/show.blade.php
@extends('layouts.master')

@section('title')
    Halaman Detail Genre
@endsection
 
@section('content')

<h1 class="text-primary">{{ $genre->nama }}</h1>
<p>{{ $genre->deskripsi }}</p>

<div class="row">
    @forelse ($genre->film as $value)
    <div class="col-4">
        <div class="card" style="width: 18rem;">
            <img src="{{ asset('/image/'.$value->poster) }}" height="200px" class="card-img-top" alt="...">
            <div class="card-body">
              <h2>{{ $value->judul }}</h2>
              <p class="card-text">{{ Str::limit($value->ringkasan, 30) }}</p>
                <div class="row">
                     <div class="col">
                  <a href="/film/{{ $value->id }}" class="btn btn-primary btn-block btn-sm">Detail</a>
                     </div>
                 </div>
            </div>
          </div>
    </div>
        @empty
            <h1>Tidak ada berita</h1>
        @endforelse
</div>

<a href="{{ route('genre.index') }}" class="btn btn-primary btn-sm">Kembali</a>

@endsection

resources/views/genre/tambah.blade.php
@extends('layouts.master')

@section('title')
    Halaman Tambah Genre
@endsection

@section('content')
<form method="post" action="{{ route('genre.store') }}">
  @csrf
  <div class="form-group">
    <label for="nama">Nama Genre</label>
    <input type="text" class="form-control" name="nama" id="nama" value="{{ old('nama') }}">
  </div>
  @error('nama')
      <div class="alert alert-danger">{{ $message }}</div>
  @enderror
  <div class="form-group">
    <label for="deskripsi">Deskripsi</label>
    <input type="text" class="form-control" name="deskripsi" id="deskripsi"value="{{ old('deskripsi') }}">
  </div>
  @error('deskripsi')
      <div class="alert alert-danger">{{ $message }}</div>
  @enderror
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
@endsection