routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CastController;
use App\Http\Controllers\FilmController;
use App\Http\Controllers\GenreController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\UlasanController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index']);
Route::get('/register', [AuthController::class, 'register']);
Route::post('/welcome', [AuthController::class, 'welcome']);

Route::view('/data-table', 'data-table');
Route::view('/table', 'table');

Route::middleware(['auth'])->group(function () {
  // route untuk mengarah ke form tambah cast
  Route::get('/cast/create', [CastController::class, 'create'])->name('cast.create');
  // route untuk menyimpan data inputan ke db
  Route::post('/cast', [CastController::class, 'store'])->name('cast.store');
  // menampilkan semua data yang di db
  Route::get('/cast', [CastController::class, 'index'])->name('cast.index');
  // detail cast berdasarkan id
  Route::get('/cast/{cast_id}', [CastController::class, 'show'])->name('cast.show');
  // untuk mengarah ke halaman form update berdasarkan id
  Route::get('/cast/{cast_id}/edit', [CastController::class, 'edit'])->name('cast.edit');
  // untuk update data
  Route::put('/cast/{cast_id}', [CastController::class, 'update'])->name('cast.update');
  // menghapus data
  Route::delete('/cast/{cast_id}', [CastController::class, 'destroy'])->name('cast.destroy');

  Route::resource('profile', ProfileController::class)->only('index', 'update');
  Route::resource('genre', GenreController::class);

  Route::post('/ulasan/{berita_id}', [UlasanController::class, 'store']);
});


Route::resource('film', FilmController::class);

Auth::routes();

app/Models/Film.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Film extends Model
{
    use HasFactory;

    protected $table = "film";
    protected $fillable = ["judul", "ringkasan", "tahun", "poster", "genre_id"];

    public function genre()
    {
        return $this->belongsTo(Genre::class, 'genre_id');
    }

    public function ulasan()
    {
        return $this->hasMany(Ulasan::class, 'film_id');
    }
}

app/Http/Controllers/FilmController.php
<?php

namespace App\Http\Controllers;

use App\Models\Film;
use App\Models\Genre;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use File;

class FilmController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth')->except(['index', 'show']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $film = Film::all();

        return view('film.index', ['film' => $film]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $genre = Genre::all();
        return view('film.tambah', ['genre' => $genre]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'judul' => ['required'],
            'ringkasan' => ['required'],
            'tahun' => ['required'],
            'poster' => ['required', 'mimes:jpg,jpeg,png', 'max:2048'],
            'genre_id' => ['required']
        ]);

        // menggunakan unik name
        // $namaPoster = time() . '.' . $request->poster->extension();
        // Menggunakan Slug
        $namaPoster = Str::slug($request->judul, '-') . '.' . $request->poster->extension();

        $request->poster->move(public_path('image'), $namaPoster);

        $film = new Film;

        $film->judul = $request->judul;
        $film->ringkasan = $request->ringkasan;
        $film->tahun = $request->tahun;
        $film->poster = $namaPoster;
        $film->genre_id = $request->genre_id;

        $film->save();

        return redirect('/film');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $film = Film::find($id);
        return view('film.detail', ['film' => $film]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $genre = Genre::all();
        $film = Film::find($id);
        return view('film.edit', [
            'film' => $film,
            'genre' => $genre
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'judul' => ['required'],
            'ringkasan' => ['required'],
            'tahun' => ['required'],
            'poster' => ['required', 'mimes:jpg,jpeg,png', 'max:2048'],
            'genre_id' => ['required']
        ]);

        $film = Film::find($id);

        if ($request->has('gambar')) {
            $path = 'image/';
            File::delete($path . $film->poster);

            $namaPoster = time() . '.' . $request->poster->extension();

            $request->poster->move(public_path('image'), $namaPoster);

            $film->poster = $namaPoster;

            $film->save();
        }

        $film->judul = $request->judul;
        $film->ringkasan = $request->ringkasan;
        $film->tahun = $request->tahun;
        $film->poster = $namaPoster;
        $film->genre_id = $request->genre_id;

        $film->save();

        return redirect('/film');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $film = Film::find($id);

        $path = 'image/';
        File::delete($path . $film->poster);

        $film->delete();

        return redirect('/film');
    }
}

resources/views/film/detail.blade.php
@extends('layouts.master')

@section('title')
    Halaman Detail Film
@endsection

@push('scripts')
    <script src="https://cdn.tiny.cloud/1/32f7rj0gbe0nv9nemz12w2i7ilovqx57pagff68g13po1bvb/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    <script>
        tinymce.init({
            selector: 'textarea',
            plugins: 'advlist autolink lists link image charmap preview anchor pagebreak',
            toolbar_mode: 'floating',
        });
    </script>
@endpush

@section('content')

<img src="{{ asset('/image/'.$film->poster) }}" height="200px" class="card-img-top" alt="...">
<div class="card-body">
<h2>{{ $film->judul }}</h2>
<p class="card-text my-4">{{ $film->ringkasan }}</p>

<h2>List Film</h2>
@forelse ($film->ulasan as $value)
<div class="media">
    <h1 class="text-primary mr-3">{{ $value->point }}</h1>
    <div class="media-body">
      <h5 class="mt-0">{{ $value->user->name }} ({{ $value->user->profile->umur }})</h5>
      <p>{!!$value->konten!!}</p>
    </div>
  </div>
@empty
    <h1>Tidak ada komentar</h1>
@endforelse




<form action="/ulasan/{{ $film->id }}" method="post">
@csrf
<select name="point" id="point" class="form-control my-2">
    <option value="">--Kasih Point--</option>
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
    <option value="4">4</option>
    <option value="5">5</option>
</select>
<textarea name="konten" id="konten" cols="30" rows="10" class="form-control my-2" placeholder="Berikan komentar.."></textarea>

<input type="submit" value="Tambah" class="btn btn-info btn-sm btn-block my-2">
</form>

<a href="{{ route('film.index') }}" class="btn btn-secondary btn-sm">Kembali</a>

@endsection

resources/views/film/edit.blade.php
@extends('layouts.master')

@section('title')
    Halaman Edit Film
@endsection

@section('content')
<form method="post" action="{{ route('film.update') }}" enctype="multipart/form-data">
  @csrf
  @method('put')
  <div class="form-group">
    <label for="judul">Judul Film</label>
    <input type="text" class="form-control" name="judul" id="judul" value="{{ old('judul', $film->judul) }}">
  </div>
  @error('judul')
      <div class="alert alert-danger">{{ $message }}</div>
  @enderror
  <div class="form-group">
    <label for="tahun">Tahun Film</label>
    <input type="text" class="form-control" name="tahun" id="tahun"value="{{ old('tahun', $film->tahun) }}">
  </div>
  @error('tahun')
      <div class="alert alert-danger">{{ $message }}</div>
  @enderror
  <div class="form-group">
    <label for="genre_id">Genre Film</label>
    <select name="genre_id" id="genre_id" class="form-control">
      <option value="">---Pilih Genre---</option>
      @forelse ($genre as $value)
        @if ($value->id === $film->genre_id)
        <option value="{{ $value->id }} " selected>{{ $value->nama }}</option>
        @else 
        <option value="{{ $value->id }}">{{ $value->nama }}</option>
        @endif

      @empty
          Tidak Ada Genre
      @endforelse
    </select>
  </div>
  @error('genre_id')
      <div class="alert alert-danger">{{ $message }}</div>
  @enderror
  <div class="form-group">
    <label for="ringkasan">Ringkasan Film</label>
    <textarea class="form-control" cols="30" rows="10" name="ringkasan" id="ringkasan">{{ old('ringkasan') }}</textarea>  
  </div>
  @error('ringkasan')
      <div class="alert alert-danger">{{ $message }}</div>
  @enderror
  <div class="form-group">
    <label for="poster">Poster Film</label>
    <input type="file" class="form-control" name="poster" id="poster">
  </div>
  @error('poster')
      <div class="alert alert-danger">{{ $message }}</div>
  @enderror
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
@endsection

resources/views/film/index.blade.php
@extends('layouts.master')

@section('title')
    Halaman List Film
@endsection

@section('content')
@auth
<a href="{{ route('film.create') }}" class="btn btn-primary btn-sm my-3">Tambah Film</a>
@endauth
<div class="row">
  @foreach ($film as $value)
  <div class="col-4">
    <div class="card" style="width: 18rem;">
      <img src="{{ asset('/image/'.$value->poster) }}" height="200px" class="card-img-top" alt="...">
      <div class="card-body">
        <h2>{{ $value->judul }}</h2>
        <p class="card-text">{{ Str::limit($value->ringkasan, 30) }}</p>
        <span class="badge badge-info">{{ $value->genre->nama }}</span>
        <div class="row">
          <div class="col">
            <a href="/film/{{ $value->id }}" class="btn btn-primary btn-block btn-sm">Detail</a>
          </div>
          @auth
          <div class="col">
            <a href="/film/{{ $value->id }}/edit" class="btn btn-warning btn-block btn-sm">Update</a>
          </div>
          <div class="col">
            <form action="/film/{{ $value->id }}" method="post">
            @csrf
            @method('delete')
            <input type="submit" value="Delete" class="btn btn-danger btn-block btn-sm">
            </form>
          </div>
          @endauth
        </div>
      </div>
    </div>
  </div>
  @endforeach
</div>


@endsection

resources/views/film/tambah.blade.php
@extends('layouts.master')

@section('title')
    Halaman Tambah Film
@endsection

@section('content')
<form method="post" action="{{ route('film.index') }}" enctype="multipart/form-data">
  @csrf
  <div class="form-group">
    <label for="judul">Judul Film</label>
    <input type="text" class="form-control" name="judul" id="judul" value="{{ old('judul') }}">
  </div>
  @error('judul')
      <div class="alert alert-danger">{{ $message }}</div>
  @enderror
  <div class="form-group">
    <label for="tahun">Tahun Film</label>
    <input type="text" class="form-control" name="tahun" id="tahun"value="{{ old('tahun') }}">
  </div>
  @error('tahun')
      <div class="alert alert-danger">{{ $message }}</div>
  @enderror
  <div class="form-group">
    <label for="genre_id">Genre Film</label>
    <select name="genre_id" id="genre_id" class="form-control">
      <option value="">---Pilih Genre---</option>
      @forelse ($genre as $value)
          <option value="{{ $value->id }}">{{ $value->nama }}</option>
      @empty
          Tidak Ada Genre
      @endforelse
    </select>
  </div>
  @error('genre_id')
      <div class="alert alert-danger">{{ $message }}</div>
  @enderror
  <div class="form-group">
    <label for="ringkasan">Ringkasan Film</label>
    <textarea class="form-control" cols="30" rows="10" name="ringkasan" id="ringkasan">{{ old('ringkasan') }}</textarea>  
  </div>
  @error('ringkasan')
      <div class="alert alert-danger">{{ $message }}</div>
  @enderror
  <div class="form-group">
    <label for="poster">Poster Film</label>
    <input type="file" class="form-control" name="poster" id="poster">
  </div>
  @error('poster')
      <div class="alert alert-danger">{{ $message }}</div>
  @enderror
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
@endsection